name: Simple App Pipeline

on:
  push:
  pull_request:

jobs:

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep scan --config=auto --json > semgrep-report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Semgrep Summary
        run: |
          echo "## 🔍 SAST Findings (Semgrep)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| File | Line | Rule | Severity | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|------|---------|-------------|" >> $GITHUB_STEP_SUMMARY

          jq -r '.results[] |
            "| \(.path) | \(.start.line) | \(.check_id) | \(.extra.severity) | \(.extra.message) |"
          ' semgrep-report.json >> $GITHUB_STEP_SUMMARY

  dependency_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
          output: trivy-fs-report.txt
        env:
          TRIVY_DISABLE_VEX_NOTICE: true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.txt

      - name: Trivy Dependency Scan Summary
        run: |
          echo "## 🐳 Dependency Vulnerabilities (Trivy)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat trivy-fs-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  build_and_scan_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t simple-app-python .

      - name: Scan container image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: simple-app-python
          severity: CRITICAL,HIGH
          output: trivy-container-report.txt
        env:
          TRIVY_DISABLE_VEX_NOTICE: true

      - name: Upload Trivy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-container-report
          path: trivy-container-report.txt
      
      - name: Trivy Container Image Scan Summary
        run: |
          echo "## 🐳 Container Image Vulnerabilities (Trivy)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat trivy-container-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run app
        run: |
          docker build -t simple-app-python .
          docker run -d -p 8080:8080 simple-app-python

      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://localhost:8080/'
          allow_issue_writing: false
          artifact_name: zap-scan-report

      - name: OWASP ZAP Summary
        run: |
          echo "## 🌐 DAST Findings (OWASP ZAP)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| URL | Risk | Vulnerability | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|------|--------------|-------------|" >> $GITHUB_STEP_SUMMARY

          jq -r '.site[].alerts[] |
            "| \(.instances[0].uri) | \(.riskdesc) | \(.alert) | \(.desc | gsub("\n"; " ")) |"
          ' report_json.json >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: [sast, dependency_scan, build_and_scan_container, dast]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy project files to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_EC2 }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/ubuntu/app"

      - name: Execute Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            docker-compose down
            docker-compose up -d --build
            
            docker image prune -f
